
import matplotlib.pyplot as plt
plt.figure(figsize=(10,6))
plt.plot([0.5, 1, 1.5, 2, 2.5, 3], [0.5, 2, 4.5, 8, 12.5, 18], 'r-o', label="Power(W)")
plt.xlabel('Voltage(V)')
plt.ylabel('Current(A)')
plt.title('Power generated by a circuit with changing voltage levels')
plt.xticks([0.5, 1, 1.5, 2, 2.5, 3])
plt.legend(loc='upper left')
plt.grid()

for x, y in zip([0.5, 1, 1.5, 2, 2.5, 3], [0.5, 2, 4.5, 8, 12.5, 18]):
    plt.annotate(str(y), xy=(x, y), xytext=(x - 0.1, y + 0.5))
plt.tight_layout()
plt.savefig('line chart/png/561.png')
plt.clf()