import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
from matplotlib.colors import Normalize

data = np.array([
    [2690, 85, 60, 7],
    [1000, 20, 30, 8],
    [330, 3, 11, 6],
    [310, 2, 7, 8],
    [280, 1, 5, 7],
    [250, 1, 4, 8]
])

data_labels = ['Active Users (Millions)', 'Revenue (Billion $)', 'Market Share (%)', 'User Satisfaction (Score)']

line_labels = ['Facebook', 'Instagram', 'Twitter', 'LinkedIn', 'Snapchat', 'Pinterest']

fig, ax = plt.subplots(figsize=(12, 8))

cmap = cm.get_cmap('viridis')

for i, line_label in enumerate(line_labels):
    size = (data[i, 2] - np.min(data[:, 2])) / (np.max(data[:, 2]) - np.min(data[:, 2])) * (5000 - 600) + 600
    color = (data[i, 3] - np.min(data[:, 3])) / (np.max(data[:, 3]) - np.min(data[:, 3]))
    ax.scatter(data[i, 0], data[i, 1], label=None, s=size, c=[cmap(color)])
    ax.scatter([], [], c=cmap(color), label=f'{line_label} {data[i, 2]}')

ax.legend(title=data_labels[2])
ax.grid(True)

cbar = plt.colorbar(cm.ScalarMappable(norm=Normalize(np.min(data[:, 3]), np.max(data[:, 3])), cmap=cmap))
cbar.ax.get_yaxis().labelpad = 15
cbar.ax.set_title(data_labels[3])

ax.set_xlabel(data_labels[0], wrap=True)
ax.set_ylabel(data_labels[1], wrap=True)

plt.title('User Engagement and Revenue Generated by Internet Platforms 2023')

plt.tight_layout()
plt.savefig('/cpfs01/user/yehancheng/workspace/datasets/SimChartV2/demo/bubble/png/299_202312310045.png')

plt.clf()
