
import matplotlib.pyplot as plt
fig=plt.figure(figsize=(8,4))
ax=fig.add_subplot(111)
ax.bar(['USA','UK','Germany','France'], [80,75,82,78], width=0.5, label='Average Grades', bottom=0)
ax.bar(['USA','UK','Germany','France'], [8,10,6,7], width=0.5, label='Dropout Rates', bottom=[80,75,82,78])
plt.xticks(['USA','UK','Germany','France'])
plt.title('Average Grades and Dropout Rates of Countries in 2021')
plt.legend()
ax.text(0.1, 78, '80', va='center', ha='center',color='white',fontsize=12)
ax.text(0.6, 75, '75', va='center', ha='center',color='white',fontsize=12)
ax.text(1.1, 82, '82', va='center', ha='center',color='white',fontsize=12)
ax.text(1.6, 78, '78', va='center', ha='center',color='white',fontsize=12)
ax.text(0.1, 8, '8%', va='center', ha='center',color='white',fontsize=12)
ax.text(0.6, 10, '10%', va='center', ha='center',color='white',fontsize=12)
ax.text(1.1, 6, '6%', va='center', ha='center',color='white',fontsize=12)
ax.text(1.6, 7, '7%', va='center', ha='center',color='white',fontsize=12)
plt.tight_layout()
plt.savefig('Bar Chart/png/232.png')
plt.cla()