
import matplotlib.pyplot as plt
fig = plt.figure(figsize=(10,6))
ax = fig.add_subplot(111)
ax.bar(1, 90, width=0.2, label='English', color='gray')
ax.bar(1.2, 92, width=0.2, label='Math', color='blue')
ax.bar(1.4, 80, width=0.2, label='Science', color='green')
ax.bar(2, 85, width=0.2, color='gray')
ax.bar(2.2, 86, width=0.2, color='blue')
ax.bar(2.4, 82, width=0.2, color='green')
ax.bar(3, 88, width=0.2, color='gray')
ax.bar(3.2, 90, width=0.2, color='blue')
ax.bar(3.4, 84, width=0.2, color='green')
ax.bar(4, 87, width=0.2, color='gray')
ax.bar(4.2, 93, width=0.2, color='blue')
ax.bar(4.4, 86, width=0.2, color='green')
ax.set_title('Percentage of English, Math, and Science grades in four grades', fontsize=14)
ax.set_xlabel('Grades')
ax.set_ylabel('Percentage')
ax.set_xticks([1.2, 2.2, 3.2, 4.2])
ax.set_xticklabels(['Grade 1','Grade 2','Grade 3','Grade 4'], rotation=0, fontsize=12)
ax.legend(loc='upper center', bbox_to_anchor=(0.5, 1.1), ncol=3, fancybox=True, shadow=True)
plt.tight_layout()
fig.savefig('bar chart/png/4.png')
plt.clf()