
import matplotlib.pyplot as plt
plt.figure(figsize=(9,5))
ax=plt.subplot()
ax.bar('USA',500,bottom=0,width = 0.2,label='Literature')
ax.bar('USA',450,bottom=500,width = 0.2,label='Music')
ax.bar('USA',400,bottom=950,width = 0.2,label='Theatre')
ax.bar('UK',600,bottom=0,width = 0.2,label='Literature')
ax.bar('UK',500,bottom=600,width = 0.2,label='Music')
ax.bar('UK',500,bottom=1100,width = 0.2,label='Theatre')
ax.bar('Germany',500,bottom=0,width = 0.2,label='Literature')
ax.bar('Germany',400,bottom=500,width = 0.2,label='Music')
ax.bar('Germany',350,bottom=900,width = 0.2,label='Theatre')
ax.bar('France',550,bottom=0,width = 0.2,label='Literature')
ax.bar('France',450,bottom=550,width = 0.2,label='Music')
ax.bar('France',420,bottom=1000,width = 0.2,label='Theatre')
plt.title("Number of social sciences and humanities achievements in four countries in 2021")
plt.xticks(["USA","UK","Germany","France"],rotation=45,ha='right')
plt.legend(loc='upper right')
plt.tight_layout()
plt.savefig('bar chart/png/185.png')
plt.clf()