
import matplotlib.pyplot as plt
plt.figure(figsize=(8, 6))
ax = plt.subplot()
ax.bar('North America', 1000, bottom=0, label='Renewable Energy (MW)', color='#2ca02c')
ax.bar('North America', 1500, bottom=1000, label='Non-Renewable Energy (MW)', color='#d62728')
ax.bar('South America', 900, bottom=0, label='Renewable Energy (MW)', color='#2ca02c')
ax.bar('South America', 1600, bottom=900, label='Non-Renewable Energy (MW)', color='#d62728')
ax.bar('Europe', 1200, bottom=0, label='Renewable Energy (MW)', color='#2ca02c')
ax.bar('Europe', 1800, bottom=1200, label='Non-Renewable Energy (MW)', color='#d62728')
ax.bar('Asia', 1100, bottom=0, label='Renewable Energy (MW)', color='#2ca02c')
ax.bar('Asia', 1700, bottom=1100, label='Non-Renewable Energy (MW)', color='#d62728')
ax.set_title('Comparison of Renewable and Non-Renewable Energy Usage in different regions in 2021')
ax.set_ylabel('Energy Usage (MW)')
ax.set_xticklabels(['North America', 'South America', 'Europe', 'Asia'], rotation=45, ha="right", wrap=True)
plt.legend(loc='upper left')
plt.tight_layout()
plt.savefig(r'bar chart/png/398.png')
plt.clf()